global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  - job_name: 'ml_model'
    static_configs:
      - targets: ['app:8001']

  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]